name: MazterSamzz Demo Action
description: This action greets persons

inputs:
  person:
    description: 'Who to greet'
    required: true
    default: 'Monolisa Octocat'

runs:
  using: node24
  main: dist/index.js
